/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jogo.telas;

/**
 *
 * @author Julimar
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        
        btnJogador.setBackground(new java.awt.Color(0xb3e0e6));
        btnPlacar.setBackground(new java.awt.Color(0xb3e0e6));
    }

    TelaCadJogador cadastro = new TelaCadJogador();
    TelaPlacar placar = new TelaPlacar();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJogador = new javax.swing.JButton();
        btnPlacar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Inicial");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jogo/img/jogar.png"))); // NOI18N
        btnJogador.setToolTipText("Jogar");
        btnJogador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJogador.setMaximumSize(new java.awt.Dimension(128, 128));
        btnJogador.setMinimumSize(new java.awt.Dimension(128, 128));
        btnJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnJogador, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 532, 128, 128));

        btnPlacar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jogo/img/placar.png"))); // NOI18N
        btnPlacar.setToolTipText("Placar");
        btnPlacar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlacarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlacar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 532, 128, 128));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jogo/img/logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jogo/img/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 0, 870, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogadorActionPerformed
        cadastro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnJogadorActionPerformed

    private void btnPlacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlacarActionPerformed
        placar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPlacarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJogador;
    private javax.swing.JButton btnPlacar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
